services:
   api:
      build: .
      volumes:
         - ./config.json:/config.json
         - ./data:/data
         - ./sslcert:/certs
         - ./app:/app/app
      ports:
         - '80:80'
         - '443:443'
      environment:
         - 'NODE_ENV=production'
