export const districts = [
	'Versorgungsgebiet Mittelrhein-Westerwald',
	'Ahrweiler',
	'Altenkirchen',
	'Cochem-Zell',
	'KS Koblenz',
	'Mayen-Koblenz',
	'Neuwied',
	'Rhein-Hunsrück',
	'Rhein-Lahn',
	'Westerwaldkreis',
	'Versorgungsgebiet Rheinhessen-Nahe',
	'Alzey-Worms',
	'Bad Kreuznach',
	'Birkenfeld',
	'Mainz-Bingen',
	'KS Mainz',
	'KS Worms',
	'Versorgungsgebiet Rheinpfalz',
	'Bad Dürkheim',
	'KS Neustadt a.d.W.',
	'KS Landau i.d.Pf.',
	'Südliche Weinstr.',
	'KS Frankenthal',
	'Rhein-Pfalz-Kreis',
	'KS Ludwigshafen',
	'Germersheim',
	'KS Speyer',
	'Versorgungsgebiet Trier',
	'Bernkastel-Wittlich',
	'Bitburg-Prüm',
	'Trier-Saarburg',
	'KS Trier',
	'Vulkaneifel',
	'Versorgungsgebiet Westpfalz',
	'Donnersbergkreis',
	'Kaiserslautern',
	'KS Kaiserslautern',
	'Kusel',
	'KS Pirmasens',
	'Südwestpfalz',
	'KS Zweibrücken',
	'Rheinland-Pfalz',
];

export const Versorgungsgebiet = [
	{
		name: 'Versorgungsgebiet Mittelrhein-Westerwald',
		districts: [
			'Ahrweiler',
			'Altenkirchen',
			'Cochem-Zell',
			'KS Koblenz',
			'Mayen-Koblenz',
			'Neuwied',
			'Rhein-Hunsrück',
			'Rhein-Lahn',
			'Westerwaldkreis',
		],
	},
	{
		name: 'Versorgungsgebiet Rheinhessen-Nahe',
		districts: [
			'Alzey-Worms',
			'Bad Kreuznach',
			'Birkenfeld',
			'Mainz-Bingen',
			'KS Mainz',
			'KS Worms',
		],
	},
	{
		name: 'Versorgungsgebiet Rheinpfalz',
		districts: [
			'Bad Dürkheim',
			'KS Neustadt a.d.W.',
			'KS Landau i.d.Pf.',
			'Südliche Weinstr.',
			'KS Frankenthal',
			'Rhein-Pfalz-Kreis',
			'KS Ludwigshafen',
			'Germersheim',
			'KS Speyer',
		],
	},
	{
		name: 'Versorgungsgebiet Trier',
		districts: [
			'Bernkastel-Wittlich',
			'Bitburg-Prüm',
			'Trier-Saarburg',
			'KS Trier',
			'Vulkaneifel',
		],
	},
	{
		name: 'Versorgungsgebiet Westpfalz',
		districts: [
			'Donnersbergkreis',
			'Kaiserslautern',
			'KS Kaiserslautern',
			'Kusel',
			'KS Pirmasens',
			'Südwestpfalz',
			'KS Zweibrücken',
		],
	},
	{
		name: 'Rheinland-Pfalz',
		districts: ['Rheinland-Pfalz'],
	},
];
